//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.BaseData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiplomEntities : DbContext
    {
        public DiplomEntities()
            : base("name=DiplomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category_soft> Category_soft { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Licenses> Licenses { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<Producer> Producer { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Soft> Soft { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type_licenses> Type_licenses { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
