//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.BaseData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licenses
    {
        public int Id_licenses { get; set; }
        public Nullable<int> Notifications_id { get; set; }
        public Nullable<int> Status_id { get; set; }
        public Nullable<int> Soft_id { get; set; }
        public Nullable<int> Device_id { get; set; }
        public Nullable<int> User_id { get; set; }
        public Nullable<System.DateTime> Start_date { get; set; }
        public Nullable<System.DateTime> End_date { get; set; }
        public string license_key { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Notifications Notifications { get; set; }
        public virtual Soft Soft { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
