//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.BaseData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Notifications()
        {
            this.Licenses = new HashSet<Licenses>();
        }
    
        public int Id_notifications { get; set; }
        public System.DateTime Sent_date { get; set; }
        public int Status_id { get; set; }
        public int User_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Licenses> Licenses { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
