//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_F2_.BaseDate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.Licenses = new HashSet<Licenses>();
        }
    
        public int Id_device { get; set; }
        public string Name_device { get; set; }
        public string Type { get; set; }
        public int Location_id { get; set; }
        public int Status_id { get; set; }
        public Nullable<int> Producer_id { get; set; }
        public Nullable<int> User_id { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Producer Producer { get; set; }
        public virtual Status_device Status_device { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Licenses> Licenses { get; set; }
    }
}
