//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_F2_.BaseDate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licenses
    {
        public int Id_licenses { get; set; }
        public int Soft_id { get; set; }
        public string Licenses_key { get; set; }
        public Nullable<System.DateTime> Purchase_date { get; set; }
        public Nullable<System.DateTime> Expiration_date { get; set; }
        public int Device_id { get; set; }
        public int Status_id { get; set; }
        public Nullable<int> Amount_licenses { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Soft Soft { get; set; }
        public virtual Status_licenses Status_licenses { get; set; }
    }
}
