//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_F2_.BaseDate
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiplomEntities1 : DbContext
    {
        public DiplomEntities1()
            : base("name=DiplomEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departament> Departament { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<Licenses> Licenses { get; set; }
        public virtual DbSet<Locate_order> Locate_order { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Producer> Producer { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Soft> Soft { get; set; }
        public virtual DbSet<Status_device> Status_device { get; set; }
        public virtual DbSet<Status_licenses> Status_licenses { get; set; }
        public virtual DbSet<Status_order> Status_order { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
