//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_F2_.BaseDate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id_order { get; set; }
        public Nullable<int> User_id { get; set; }
        public System.DateTime Order_date { get; set; }
        public string Number { get; set; }
        public int Status_id { get; set; }
        public string Message { get; set; }
        public string Title { get; set; }
        public string Cabinet { get; set; }
        public Nullable<int> Address_id { get; set; }
        public string Reason { get; set; }
    
        public virtual Locate_order Locate_order { get; set; }
        public virtual Status_order Status_order { get; set; }
        public virtual User User { get; set; }
    }
}
